#!/usr/bin/env bash
# autoscript: file management for script(1)

storage_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}
storage_dir+="/autoscript"
version="0.1.0"

shopt -s nullglob

function create_storage_dir() {
    mkdir -p $storage_dir
}

function print_usage() {
    echo "Usage: autoscript MODE [ID]"
    echo "Available modes: record, replay, list, version"
    exit 1
}

function record_metatada() {
    # Write context information to metadata file
    local mdfile="$storage_dir"/"$1".metadata.txt
    {
        echo "DATE=$(date)"
        echo "SYSTEM=$(uname -r)"
        echo "USER=$(whoami)"
        echo "TIMINGS=true"
    } >> "$mdfile"
}

function record_mode() {
    create_storage_dir
    
    next_id=1

    # Search for the next ID to use by parsing filenames
    for filename in "$storage_dir"/*.typescript; do
        local id

        id=$(basename "$filename" | grep -Eo "^[0-9]+")
        if [[ $? -eq 0 ]] && ((id >= next_id)); then
            ((next_id = id + 1))
        fi
    done
    
    record_metatada $next_id

    # Start script(1), setting the AUTOSCRIPT variable
    # TODO: Make timings optional
    AUTOSCRIPT=true script \
        -f \
        -q \
        --timing="$storage_dir"/"$next_id".timings \
        "$storage_dir"/"$next_id".typescript
}

function list_mode() {
    create_storage_dir

    for filename in "$storage_dir"/*.typescript; do
        local id

        id=$(basename "$filename" | grep -Eo "^[0-9]+")
        if [[ $? -eq 0 ]]; then
            local mdfile="$storage_dir"/"$id".metadata.txt
            echo "$id:"            

            while IFS="=" read -r key value; do
                echo "-> $key: $value"
            done < "$mdfile"
        fi
    done
}

function replay_mode() {
    create_storage_dir
    local typescript="$storage_dir"/"$1".typescript

    if [[ -f "$typescript" ]]; then
        echo "========== BEGIN REPLAY =========="
        cat "$typescript"
        echo "==========  END REPLAY  =========="
    else
        echo "Specified script ID not found!"
        exit 1
    fi
}

case $1 in
    record)
        if [[ -n $AUTOSCRIPT ]]; then
            # Do not run autoscript inside autoscript
            exit 1
        fi
        record_mode
    ;;
    list)
        list_mode
    ;;
    replay)
        if [[ -z $2 ]]; then
            echo "Replay mode: ID not specified"
            exit 1
        fi
        replay_mode "$2"
    ;;
    version)
        echo $version
    ;;
    *)
        print_usage
    ;;
esac
