#!/usr/bin/env bash
# autoscript: file management for script(1)

readonly storage_dir="${XDG_CONFIG_HOME:-"$HOME/.config"}/autoscript"
readonly version="0.1.1"

shopt -s nullglob

function create_storage_dir() {
    mkdir -p "$storage_dir" -m 700
}

function print_usage() {
    echo "Usage: autoscript MODE [ID]"
    echo "Available modes: record, replay, list, version, context"
    exit 1
}

function create_file() {
    if [[ -f "$1" ]]; then
        echo "File already exists: $1" >&2
        exit 1
    fi
    install -m 600 /dev/null "$1"
}

function record_metatada() {
    # Write context information to metadata file
    local mdfile="$storage_dir"/"$1".metadata.txt
    create_file "$mdfile"

    {
        echo "DATE=$(date)"
        echo "SYSTEM=$(uname -r)"
        echo "USER=$(whoami)"
        echo "TIMINGS=true"
    } >> "$mdfile"
}

function record_mode() {
    create_storage_dir
    
    local quiet="$1"
    local timings="$2"
    local next_id=1

    # Search for the next ID to use by parsing filenames
    for filename in "$storage_dir"/*.typescript; do
        local id

        id=$(basename "$filename" | grep -Eo "^[0-9]+")
        if [[ $? -eq 0 ]] && ((id >= next_id)); then
            ((next_id = id + 1))
        fi
    done

    # Start script(1), setting the AUTOSCRIPT_ID variable
    # TODO: Make timings optional
    local typescript="$storage_dir"/"$next_id".typescript
    local timings="$storage_dir"/"$next_id".timings
    
    create_file "$typescript"
    create_file "$timings"
    record_metatada "$next_id"

    if [[ "$quiet" == "false" ]]; then
        echo "This session is being recorded by autoscript."
        echo "Output file: $typescript"
    fi

    AUTOSCRIPT_ID="$next_id" script \
        -f \
        -q \
        --timing="$timings" \
        "$typescript"
}

function list_mode() {
    create_storage_dir

    for filename in "$storage_dir"/*.typescript; do
        local id

        id=$(basename "$filename" | grep -Eo "^[0-9]+")
        if [[ $? -eq 0 ]]; then
            local mdfile="$storage_dir"/"$id".metadata.txt
            echo "$id:"            

            while IFS="=" read -r key value; do
                echo "-> $key: $value"
            done < "$mdfile"
        fi
    done
}

function replay_mode() {
    create_storage_dir
    local typescript="$storage_dir"/"$1".typescript

    if [[ -f "$typescript" ]]; then
        echo "========== BEGIN REPLAY =========="
        cat "$typescript"
        echo "==========  END REPLAY  =========="
    else
        echo "Specified script ID not found!" >&2
        exit 1
    fi
}

function main() {
    case $1 in
        record)
            if [[ -n $AUTOSCRIPT_ID ]]; then
                # Do not run autoscript inside autoscript
                exit 1
            fi

            local quiet="false"
            local timings="false"
            local OPTIND=2

            while getopts ":qt" opt; do
                case "$opt" in
                    q)
                        quiet="true"
                    ;;
                    t)
                        timings="true"
                    ;;
                    \?)
                        echo "Unknown option: -$OPTARG" >&2
                        exit 1
                    ;;
                esac
            done

            record_mode "$quiet" "$timings"
        ;;
        list)
            list_mode
        ;;
        replay)
            if [[ -z $2 ]]; then
                echo "Replay mode: ID not specified" >&2
                exit 1
            fi
            replay_mode "$2"
        ;;
        version)
            echo $version
        ;;
        context)
            if [[ -n $AUTOSCRIPT_ID ]]; then
                echo "$AUTOSCRIPT_ID"
            else
                echo "You are not inside an autoscript session." >&2
                exit 1
            fi
        ;;
        *)
            print_usage
        ;;
    esac
}

main "$@"
